-- Writes the rig's main.lua for one scenario, loading the mod the way lovely does.
-- Usage: luajit rig/build.lua <repo_root> <scenario_name> <out_dir>
-- <out_dir>/game is a hard-link copy of build/game made by smoke.sh; its main.lua
-- is removed first, so the write below never goes through a link into build/game.
--
-- Layout of the generated main.lua:
--   1. rig prelude: package.preload for every [patches.module] (lovely's "before main.lua")
--   2. copy patches with position = "prepend"
--   3. the vanilla main.lua, verbatim
--   4. copy patches with position = "append" (text-concatenated, as lovely does)
--   5. the rig driver, which hooks love.update and runs the scenario
local root, name, out = arg[1], arg[2], arg[3]
if not (root and name and out) then
  io.stderr:write('usage: luajit rig/build.lua <repo_root> <scenario> <out_dir>\n'); os.exit(2)
end

package.path = root..'/rig/?.lua;'..package.path
local toml = require('toml')

local function slurp(p)
  local f, err = io.open(p, 'rb')
  if not f then error('cannot read '..p..': '..tostring(err), 0) end
  local s = f:read('*a'); f:close(); return s
end

-- Every mod under mods/ with a lovely.toml, ordered by [manifest] priority, then name.
-- Our mods must not depend on append order between mods (they require each other by
-- module name instead), so this order only makes runs deterministic.
-- MODS_ROOT points the rig at another Mods-style folder instead, e.g. the extracted
-- release zip (make smoke-dist). A scenario whose header has a `-- rig-mods: A, B`
-- line loads only those mods (missing_bhcore boots without bh-core).
local mods_root = os.getenv('MODS_ROOT') or root..'/mods'
local only
do
  local fh = io.open(root..'/rig/scenarios/'..name..'.lua', 'rb')
  local list = fh and ('\n'..fh:read('*a')):match('\n%-%- rig%-mods: ([^\n]+)')
  if fh then fh:close() end
  if list then
    only = {}
    for id in list:gmatch('[^,%s]+') do only[id] = true end
  end
end
-- Like lovely, a mod folder's patch files are its lovely.toml and every lovely/*.toml
-- (the release bundle keeps one per mod there); sources are relative to the folder.
-- Each patch file is sorted on its own [manifest] priority.
local mods = {}
local function add_patch_file(dir, rel)
  local m = toml.parse(slurp(mods_root..'/'..dir..'/'..rel), dir..'/'..rel)
  m.dir, m.id = mods_root..'/'..dir, dir..'/'..rel
  mods[#mods+1] = m
end
local ls = io.popen('ls -1 '..mods_root..' 2>/dev/null')
for dir in ls:lines() do
  if not only or only[dir] then
    local fh = io.open(mods_root..'/'..dir..'/lovely.toml', 'rb')
    if fh then fh:close(); add_patch_file(dir, 'lovely.toml') end
    local sub = io.popen('ls -1 '..mods_root..'/'..dir..'/lovely/*.toml 2>/dev/null')
    for path in sub:lines() do add_patch_file(dir, 'lovely/'..path:match('[^/]+$')) end
    sub:close()
  end
end
ls:close()
if not mods[1] then error('no lovely patch files under '..mods_root, 0) end
table.sort(mods, function(a, b)
  if a.priority ~= b.priority then return a.priority < b.priority end
  return a.id < b.id
end)

local parts = {}
local function add(s) parts[#parts+1] = s end

add('-- GENERATED by rig/build.lua for smoke scenario '..name..'. Do not edit.\n')
add('-- [rig] lovely module patches -> package.preload\n')
for _, mod in ipairs(mods) do for _, m in ipairs(mod.modules) do
  local path = mod.dir..'/'..m.source
  slurp(path) -- fail at build time, not at require time, if a source is missing
  add(string.format('package.preload[%q] = function(...) return assert(loadfile(%q))(...) end\n', m.name, path))
end end

-- Until the driver installs its own handler, a mod or game error while main.lua loads
-- (e.g. a mod module raising at require time) fails fast instead of sitting on
-- the vanilla crash screen until the wall clock.
add(string.format([[
function love.errorhandler(msg)
  msg = tostring(msg)
  io.stderr:write('[smoke] load error: ', msg, '\n', debug.traceback('', 2), '\n')
  local f = io.open(%q, 'wb')
  if f then f:write('FAIL: load error: ', (msg:gsub('\n', ' ')), '\n'); f:close() end
end
]], out..'/result.txt'))

local prepend, append = {}, {}
for _, mod in ipairs(mods) do for _, c in ipairs(mod.copies) do
  if c.target ~= 'main.lua' then
    error('copy patch targets '..c.target..'; the smoke rig only emulates main.lua', 0)
  end
  for _, src in ipairs(c.sources) do
    local list = c.position == 'prepend' and prepend or append
    list[#list+1] = {src = mod.id:match('^[^/]+')..'/'..src, text = slurp(mod.dir..'/'..src)}
  end
end end

for _, p in ipairs(prepend) do add('\n-- [rig] lovely copy (prepend): '..p.src..'\n'..p.text..'\n') end
add('\n-- [rig] vanilla main.lua\n'..slurp(root..'/build/game/main.lua')..'\n')
for _, p in ipairs(append) do add('\n-- [rig] lovely copy (append): '..p.src..'\n'..p.text..'\n') end

add('\n-- [rig] scenario driver\n')
add(string.format('assert(loadfile(%q))({root = %q, name = %q, out = %q, scenario = %q})\n',
  root..'/rig/driver.lua', root, name, out, root..'/rig/scenarios/'..name..'.lua'))

local target = out..'/game/main.lua'
os.remove(target)
local f = assert(io.open(target, 'wb'))
f:write(table.concat(parts)); f:close()
